name: Deploy to Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 追加: Azure CLI用のログイン処理
      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set App Service Settings
        run: |
          az webapp config appsettings set \
            --name 'app-my-cool-app' \
            --resource-group sandbox \
            --settings NEXT_PUBLIC_KEY='${{ secrets.KEY }}' 
            SCM_DO_BUILD_DURING_DEPLOYMENT=true

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-my-cool-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
